# 🧩 Tierphysio Manager – AutoFix Integration mit IntegrityCheck
# Erstellt für https://ew.makeit.uno von Florian Engelhardt ©2025

defaults:
  run_on_every_prompt: true

tasks:
  - name: "Tierphysio Auto-Integrity"
    trigger: ["beforePrompt", "beforeCommit"]
    action:
      run: |
        echo "🔍 Prüfe https://ew.makeit.uno/integrity.php ..."
        REPORT=$(curl -s https://ew.makeit.uno/integrity.php)

        echo "$REPORT" | grep "⚠️" && echo "⚠️ Warnungen erkannt – Starte Auto-Fix..." || echo "✅ Keine Probleme erkannt."

        # --- 1. Fehlende base.twig Erweiterung hinzufügen ---
        echo "$REPORT" | grep "erweitert keine base.twig" | awk '{print $3}' | while read FILE; do
          if [ -f "$FILE" ]; then
            if ! grep -q "{% extends 'base.twig' %}" "$FILE"; then
              sed -i '1i {% extends "base.twig" %}' "$FILE"
              echo "🛠️ base.twig-Erweiterung hinzugefügt: $FILE"
            fi
          fi
        done

        # --- 2. Fehlende endblock am Ende ergänzen ---
        echo "$REPORT" | grep "kein endblock" | awk '{print $3}' | while read FILE; do
          if [ -f "$FILE" ]; then
            if ! grep -q "{% endblock %}" "$FILE"; then
              echo "{% endblock %}" >> "$FILE"
              echo "🛠️ endblock ergänzt: $FILE"
            fi
          fi
        done

        # --- 3. Header Topbar prüfen & ggf. ergänzen ---
        HEADER="includes/layout/header.php"
        if [ -f "$HEADER" ]; then
          if ! grep -q "topbar" "$HEADER"; then
            sed -i '2i <!-- AutoFix: Topbar ergänzt -->\n<div class="topbar"></div>' "$HEADER"
            echo "🛠️ Topbar ergänzt in header.php"
          fi
        fi

        # --- 4. Modals mit fehlendem z-index reparieren ---
        echo "$REPORT" | grep "Modal ohne z-index" | awk '{print $2}' | while read PHPFILE; do
          if [ -f "$PHPFILE" ]; then
            sed -i 's/<div class="modal"/<div class="modal" style="z-index:1050"/g' "$PHPFILE"
            echo "🛠️ Modal z-index korrigiert in: $PHPFILE"
          fi
        done

        # --- 5. Footer Fix: position fixed → relative ---
        CSS="public/css/main.css"
        if [ -f "$CSS" ]; then
          if grep -q "position: fixed" "$CSS"; then
            sed -i 's/position: fixed/position: relative/g' "$CSS"
            echo "🛠️ Footerposition korrigiert (relative)."
          fi
        fi

        echo "✅ Auto-Fix abgeschlossen. Integritätsprüfung kann erneut gestartet werden."            grep -q "topbar" includes/layout/header.php || \
              sed -i '2i <!-- 🧩 Auto-Fix: Topbar hinzugefügt -->\n<div class="topbar"></div>' includes/layout/header.php
            echo "🛠️ Header geprüft und ggf. korrigiert."
          fi

          find . -type f -name "*.php" | while read php; do
            if grep -q "modal" "$php" && ! grep -q "z-index" "$php"; then
              sed -i 's/<div class="modal"/<div class="modal" style="z-index:1050"/g' "$php"
              echo "🛠️ Modal z-index repariert: $php"
            fi
          done
          
          # 4️⃣ CSS Fix für Footer
          if grep -q "position: fixed" public/css/main.css; then
            sed -i 's/position: fixed/position: relative/g' public/css/main.css
            echo "🛠️ Footer Fix: position nun relative."
          fi

          # 5️⃣ Abschließende Kontrolle
          echo "✅ Auto-Fix abgeschlossen. Bitte integrity.php neu laden und prüfen!"
        else
          echo "✅ Integritätsprüfung bestanden – keine Korrekturen nötig."
        fi
